x1 = input(f"Give me the first number: ")
x2 = input(f"Give me the second number: ")
x1,x2 = int(x1),int(x2)
print("Thank you!")
print(f"{x1} + {x2} = {int(x1+x2)}")
print(f"{x1} - {x2} = {int(x1-x2)}")
print(f"{x1} / {x2} = {int(x1/x2)}")
print(f"{x1} * {x2} = {int(x1*x2)}")
